### ISSUE TITLE
Business_Data_Analyst_Technovalley

### ISSUE THREAD

**Issue by RohitKV1n0d** [Hash-It-Solutions/technovalley-web#20]
- [x] hero image
- [x] Requisite
- [x] tools covered
- [x] about domain
- [x] CURRICULUM

**Comment by RohitKV1n0d** [comment]
@MAHESH-M-B  Please take over

**Comment by MAHESH-M-B** [comment]
finished

**Comment by MAHESH-M-B** [comment]
finished
