### ISSUE TITLE
DevOps_Engineer_Technovalley

### ISSUE THREAD

**Issue by RohitKV1n0d** [Hash-It-Solutions/technovalley-web#22]
- [x] hero image
- [x] Requisite
- [x] tools covered
- [x] about domain
- [x] CURRICULUM

**Comment by RohitKV1n0d** [comment]
@jithinse Please take over

**Comment by MAHESH-M-B** [comment]
finished

**Comment by a-humanthing** [comment]
please verify and give feedback
