### ISSUE TITLE
Mean_Stack_Technovalley

### ISSUE THREAD

**Issue by RohitKV1n0d** [Hash-It-Solutions/technovalley-web#26]
- [x] hero image
- [x] Requisite
- [x] tools covered
- [x] about domain
- [x] CURRICULUM

**Comment by MAHESH-M-B** [comment]
finished

**Comment by RohitKV1n0d** [comment]
Please review it @MAHESH-M-B

**Comment by RohitKV1n0d** [comment]
Alll checked and verifedd

**Comment by MAHESH-M-B** [comment]
finished
