### ISSUE TITLE
Threat_Hunter_Technovalley

### ISSUE THREAD

**Issue by RohitKV1n0d** [Hash-It-Solutions/technovalley-web#34]
- [ ] hero image
- [ ] Requisite
- [ ] tools covered
- [ ] about domain
- [ ] CURRICULUM

**Comment by jithinse** [comment]
completed . here tools coverd is not available in pdf

**Comment by RohitKV1n0d** [comment]
@a-humanthing please take over

**Comment by a-humanthing** [comment]
Tools images are missing
